export const REPO_URL = 'https://github.com/sabi-karami/SABI-RAY'
export const ORGANIZATION_URL = 'https://github.com/PasarGuard'
export const DONATION_URL = 'https://donate.pasarguard.org'
export const DISCUSSION_GROUP = 'https://t.me/SAHEBKARAMI'
export const DOCUMENTATION = 'https://docs.pasarguard.org'
